[control_plane]
control-plane ansible_host=195.201.95.53 private_ip=10.0.1.21

[workers]
worker-1 ansible_host=195.201.93.151 private_ip=10.0.1.20
worker-2 ansible_host=195.201.95.253 private_ip=10.0.1.10

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/hetzner_platform
ansible_python_interpreter=/usr/bin/python3
